### PR TITLE
Allow Overriding Value for Content-Security-Policy Header

### PR DESCRIPTION
**Pull request by ChexWarrior**
Hello,

We ran into a few issues with the new value (none) for the Content-Security-Policy frame-ancestors header, to get around it we ended up setting `$NGINX_NO_DEFAULT_HEADERS` to `true` and then re-adding the default headers using a custom nginx file with `$NGINX_SERVER_EXTRA_CONF_FILEPATH` so we could set the header to `self`.  I decided to create a pull request to make this process a little easier by allowing a user to customize the value of the Content-Security-Policy frame-ancestors header with a new env var: `$NGINX_CSP_FRAME_ANCESTORS`

### CODE REVIEW

**Comment by mralexho** [comment]
Would it be helpful if we can modify all headers in general? Not sure which way is better.

**Comment by ChexWarrior** [comment]
@mralexho Do you mean any header at all? In that case I think you would just use `$NGINX_SERVER_EXTRA_CONF_FILEPATH` and add the headers you want.  If you mean adding additional policies to the CSP header I'm open to it, but since the default value deals with frame-ancestors I limited my scope to modifying just that policy.

**Comment by csandanov** [comment]
I would rather have something like `$NGINX_HEADERS_CONTENT_SECURITY_POLICY`

**Comment by ChexWarrior** [comment]
@csandanov I've updated it so passing `$NGINX_HEADERS_CONTENT_SECURITY_POLICY` overrides the entire CSP header value. The default is still `frame-ancestors 'none'`.

**Pull request merged**
